/**
 * Autogenerated by Thrift Compiler (0.14.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Hello_H
#define Hello_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "hello_types.h"



#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class HelloIf {
 public:
  virtual ~HelloIf() {}
  virtual void getString(std::string& _return) = 0;
};

class HelloIfFactory {
 public:
  typedef HelloIf Handler;

  virtual ~HelloIfFactory() {}

  virtual HelloIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloIf* /* handler */) = 0;
};

class HelloIfSingletonFactory : virtual public HelloIfFactory {
 public:
  HelloIfSingletonFactory(const ::std::shared_ptr<HelloIf>& iface) : iface_(iface) {}
  virtual ~HelloIfSingletonFactory() {}

  virtual HelloIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloIf* /* handler */) {}

 protected:
  ::std::shared_ptr<HelloIf> iface_;
};

class HelloNull : virtual public HelloIf {
 public:
  virtual ~HelloNull() {}
  void getString(std::string& /* _return */) {
    return;
  }
};


class Hello_getString_args {
 public:

  Hello_getString_args(const Hello_getString_args&);
  Hello_getString_args& operator=(const Hello_getString_args&);
  Hello_getString_args() {
  }

  virtual ~Hello_getString_args() noexcept;

  bool operator == (const Hello_getString_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Hello_getString_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Hello_getString_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Hello_getString_pargs {
 public:


  virtual ~Hello_getString_pargs() noexcept;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Hello_getString_result__isset {
  _Hello_getString_result__isset() : success(false) {}
  bool success :1;
} _Hello_getString_result__isset;

class Hello_getString_result {
 public:

  Hello_getString_result(const Hello_getString_result&);
  Hello_getString_result& operator=(const Hello_getString_result&);
  Hello_getString_result() : success() {
  }

  virtual ~Hello_getString_result() noexcept;
  std::string success;

  _Hello_getString_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const Hello_getString_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Hello_getString_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Hello_getString_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Hello_getString_presult__isset {
  _Hello_getString_presult__isset() : success(false) {}
  bool success :1;
} _Hello_getString_presult__isset;

class Hello_getString_presult {
 public:


  virtual ~Hello_getString_presult() noexcept;
  std::string* success;

  _Hello_getString_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloClient : virtual public HelloIf {
 public:
  HelloClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  HelloClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getString(std::string& _return);
  void send_getString();
  void recv_getString(std::string& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<HelloIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getString(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloProcessor(::std::shared_ptr<HelloIf> iface) :
    iface_(iface) {
    processMap_["getString"] = &HelloProcessor::process_getString;
  }

  virtual ~HelloProcessor() {}
};

class HelloProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloProcessorFactory(const ::std::shared_ptr< HelloIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< HelloIfFactory > handlerFactory_;
};

class HelloMultiface : virtual public HelloIf {
 public:
  HelloMultiface(std::vector<std::shared_ptr<HelloIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloMultiface() {}
 protected:
  std::vector<std::shared_ptr<HelloIf> > ifaces_;
  HelloMultiface() {}
  void add(::std::shared_ptr<HelloIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getString(std::string& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getString(_return);
    }
    ifaces_[i]->getString(_return);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class HelloConcurrentClient : virtual public HelloIf {
 public:
  HelloConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  HelloConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getString(std::string& _return);
  int32_t send_getString();
  void recv_getString(std::string& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif



#endif
