/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "notestructure_constants.h"



const notestructureConstants g_notestructure_constants;

notestructureConstants::notestructureConstants() {
}



