// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "NoteServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class NoteServerHandler : virtual public NoteServerIf {
 public:
  NoteServerHandler() {
    // Your initialization goes here
  }

  void GetNotebooks(std::vector<Notebook> & _return, const std::string& userid) {
    // Your implementation goes here
    printf("GetNotebooks\n");
  }

  void GetContent(std::string& _return, const std::string& noteid) {
    // Your implementation goes here
    printf("GetContent\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<NoteServerHandler> handler(new NoteServerHandler());
  shared_ptr<TProcessor> processor(new NoteServerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

