/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef NoteServer_H
#define NoteServer_H

#include <thrift/TDispatchProcessor.h>
#include "notestructure_types.h"



class NoteServerIf {
 public:
  virtual ~NoteServerIf() {}
  virtual void GetNotebooks(std::vector<Notebook> & _return, const std::string& userid) = 0;
  virtual void GetContent(std::string& _return, const std::string& noteid) = 0;
};

class NoteServerIfFactory {
 public:
  typedef NoteServerIf Handler;

  virtual ~NoteServerIfFactory() {}

  virtual NoteServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(NoteServerIf* /* handler */) = 0;
};

class NoteServerIfSingletonFactory : virtual public NoteServerIfFactory {
 public:
  NoteServerIfSingletonFactory(const boost::shared_ptr<NoteServerIf>& iface) : iface_(iface) {}
  virtual ~NoteServerIfSingletonFactory() {}

  virtual NoteServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(NoteServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<NoteServerIf> iface_;
};

class NoteServerNull : virtual public NoteServerIf {
 public:
  virtual ~NoteServerNull() {}
  void GetNotebooks(std::vector<Notebook> & /* _return */, const std::string& /* userid */) {
    return;
  }
  void GetContent(std::string& /* _return */, const std::string& /* noteid */) {
    return;
  }
};


class NoteServer_GetNotebooks_args {
 public:

  NoteServer_GetNotebooks_args() : userid() {
  }

  virtual ~NoteServer_GetNotebooks_args() throw() {}

  std::string userid;

  void __set_userid(const std::string& val) {
    userid = val;
  }

  bool operator == (const NoteServer_GetNotebooks_args & rhs) const
  {
    if (!(userid == rhs.userid))
      return false;
    return true;
  }
  bool operator != (const NoteServer_GetNotebooks_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NoteServer_GetNotebooks_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NoteServer_GetNotebooks_pargs {
 public:


  virtual ~NoteServer_GetNotebooks_pargs() throw() {}

  const std::string* userid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NoteServer_GetNotebooks_result__isset {
  _NoteServer_GetNotebooks_result__isset() : success(false) {}
  bool success;
} _NoteServer_GetNotebooks_result__isset;

class NoteServer_GetNotebooks_result {
 public:

  NoteServer_GetNotebooks_result() {
  }

  virtual ~NoteServer_GetNotebooks_result() throw() {}

  std::vector<Notebook>  success;

  _NoteServer_GetNotebooks_result__isset __isset;

  void __set_success(const std::vector<Notebook> & val) {
    success = val;
  }

  bool operator == (const NoteServer_GetNotebooks_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NoteServer_GetNotebooks_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NoteServer_GetNotebooks_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NoteServer_GetNotebooks_presult__isset {
  _NoteServer_GetNotebooks_presult__isset() : success(false) {}
  bool success;
} _NoteServer_GetNotebooks_presult__isset;

class NoteServer_GetNotebooks_presult {
 public:


  virtual ~NoteServer_GetNotebooks_presult() throw() {}

  std::vector<Notebook> * success;

  _NoteServer_GetNotebooks_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class NoteServer_GetContent_args {
 public:

  NoteServer_GetContent_args() : noteid() {
  }

  virtual ~NoteServer_GetContent_args() throw() {}

  std::string noteid;

  void __set_noteid(const std::string& val) {
    noteid = val;
  }

  bool operator == (const NoteServer_GetContent_args & rhs) const
  {
    if (!(noteid == rhs.noteid))
      return false;
    return true;
  }
  bool operator != (const NoteServer_GetContent_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NoteServer_GetContent_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class NoteServer_GetContent_pargs {
 public:


  virtual ~NoteServer_GetContent_pargs() throw() {}

  const std::string* noteid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NoteServer_GetContent_result__isset {
  _NoteServer_GetContent_result__isset() : success(false) {}
  bool success;
} _NoteServer_GetContent_result__isset;

class NoteServer_GetContent_result {
 public:

  NoteServer_GetContent_result() : success() {
  }

  virtual ~NoteServer_GetContent_result() throw() {}

  std::string success;

  _NoteServer_GetContent_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const NoteServer_GetContent_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const NoteServer_GetContent_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const NoteServer_GetContent_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _NoteServer_GetContent_presult__isset {
  _NoteServer_GetContent_presult__isset() : success(false) {}
  bool success;
} _NoteServer_GetContent_presult__isset;

class NoteServer_GetContent_presult {
 public:


  virtual ~NoteServer_GetContent_presult() throw() {}

  std::string* success;

  _NoteServer_GetContent_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class NoteServerClient : virtual public NoteServerIf {
 public:
  NoteServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  NoteServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void GetNotebooks(std::vector<Notebook> & _return, const std::string& userid);
  void send_GetNotebooks(const std::string& userid);
  void recv_GetNotebooks(std::vector<Notebook> & _return);
  void GetContent(std::string& _return, const std::string& noteid);
  void send_GetContent(const std::string& noteid);
  void recv_GetContent(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class NoteServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<NoteServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (NoteServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_GetNotebooks(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_GetContent(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  NoteServerProcessor(boost::shared_ptr<NoteServerIf> iface) :
    iface_(iface) {
    processMap_["GetNotebooks"] = &NoteServerProcessor::process_GetNotebooks;
    processMap_["GetContent"] = &NoteServerProcessor::process_GetContent;
  }

  virtual ~NoteServerProcessor() {}
};

class NoteServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  NoteServerProcessorFactory(const ::boost::shared_ptr< NoteServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< NoteServerIfFactory > handlerFactory_;
};

class NoteServerMultiface : virtual public NoteServerIf {
 public:
  NoteServerMultiface(std::vector<boost::shared_ptr<NoteServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~NoteServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<NoteServerIf> > ifaces_;
  NoteServerMultiface() {}
  void add(boost::shared_ptr<NoteServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void GetNotebooks(std::vector<Notebook> & _return, const std::string& userid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetNotebooks(_return, userid);
    }
    ifaces_[i]->GetNotebooks(_return, userid);
    return;
  }

  void GetContent(std::string& _return, const std::string& noteid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetContent(_return, noteid);
    }
    ifaces_[i]->GetContent(_return, noteid);
    return;
  }

};



#endif
