/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef notestructure_CONSTANTS_H
#define notestructure_CONSTANTS_H

#include "notestructure_types.h"



class notestructureConstants {
 public:
  notestructureConstants();

};

extern const notestructureConstants g_notestructure_constants;



#endif
