/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef UserServer_H
#define UserServer_H

#include <thrift/TDispatchProcessor.h>
#include "notestructure_types.h"



class UserServerIf {
 public:
  virtual ~UserServerIf() {}
  virtual int32_t GetUserId(const std::string& username) = 0;
};

class UserServerIfFactory {
 public:
  typedef UserServerIf Handler;

  virtual ~UserServerIfFactory() {}

  virtual UserServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(UserServerIf* /* handler */) = 0;
};

class UserServerIfSingletonFactory : virtual public UserServerIfFactory {
 public:
  UserServerIfSingletonFactory(const boost::shared_ptr<UserServerIf>& iface) : iface_(iface) {}
  virtual ~UserServerIfSingletonFactory() {}

  virtual UserServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(UserServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<UserServerIf> iface_;
};

class UserServerNull : virtual public UserServerIf {
 public:
  virtual ~UserServerNull() {}
  int32_t GetUserId(const std::string& /* username */) {
    int32_t _return = 0;
    return _return;
  }
};


class UserServer_GetUserId_args {
 public:

  UserServer_GetUserId_args() : username() {
  }

  virtual ~UserServer_GetUserId_args() throw() {}

  std::string username;

  void __set_username(const std::string& val) {
    username = val;
  }

  bool operator == (const UserServer_GetUserId_args & rhs) const
  {
    if (!(username == rhs.username))
      return false;
    return true;
  }
  bool operator != (const UserServer_GetUserId_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UserServer_GetUserId_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class UserServer_GetUserId_pargs {
 public:


  virtual ~UserServer_GetUserId_pargs() throw() {}

  const std::string* username;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UserServer_GetUserId_result__isset {
  _UserServer_GetUserId_result__isset() : success(false) {}
  bool success;
} _UserServer_GetUserId_result__isset;

class UserServer_GetUserId_result {
 public:

  UserServer_GetUserId_result() : success(0) {
  }

  virtual ~UserServer_GetUserId_result() throw() {}

  int32_t success;

  _UserServer_GetUserId_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const UserServer_GetUserId_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const UserServer_GetUserId_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const UserServer_GetUserId_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _UserServer_GetUserId_presult__isset {
  _UserServer_GetUserId_presult__isset() : success(false) {}
  bool success;
} _UserServer_GetUserId_presult__isset;

class UserServer_GetUserId_presult {
 public:


  virtual ~UserServer_GetUserId_presult() throw() {}

  int32_t* success;

  _UserServer_GetUserId_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class UserServerClient : virtual public UserServerIf {
 public:
  UserServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  UserServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t GetUserId(const std::string& username);
  void send_GetUserId(const std::string& username);
  int32_t recv_GetUserId();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class UserServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<UserServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (UserServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_GetUserId(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  UserServerProcessor(boost::shared_ptr<UserServerIf> iface) :
    iface_(iface) {
    processMap_["GetUserId"] = &UserServerProcessor::process_GetUserId;
  }

  virtual ~UserServerProcessor() {}
};

class UserServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  UserServerProcessorFactory(const ::boost::shared_ptr< UserServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< UserServerIfFactory > handlerFactory_;
};

class UserServerMultiface : virtual public UserServerIf {
 public:
  UserServerMultiface(std::vector<boost::shared_ptr<UserServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~UserServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<UserServerIf> > ifaces_;
  UserServerMultiface() {}
  void add(boost::shared_ptr<UserServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t GetUserId(const std::string& username) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->GetUserId(username);
    }
    return ifaces_[i]->GetUserId(username);
  }

};



#endif
