#include "guiddefine.h"
#include "notecore.h"


DEFINE_INTERFACE_GUID(INoteCoreObj)
DEFINE_INTERFACE_GUID(INoteApplication)
DEFINE_INTERFACE_GUID(INoteCollection)
DEFINE_INTERFACE_GUID(INotebooks)
DEFINE_INTERFACE_GUID(INotebook)
DEFINE_INTERFACE_GUID(INote)
DEFINE_INTERFACE_GUID(ITrash)
DEFINE_INTERFACE_GUID(ISchedules)